// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Voter struct {
	ID        string             `json:"id"`
	FullName  string             `json:"full_name"`
	Nin       string             `json:"nin"`
	Dob       pgtype.Date        `json:"dob"`
	State     string             `json:"state"`
	Lga       string             `json:"lga"`
	Phone     string             `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	VoterID   string             `json:"voter_id"`
}
