// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PollingStation struct {
	ID        string             `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Lga       string             `json:"lga"`
	Ward      string             `json:"ward"`
	Address   *string            `json:"address"`
	Latitude  pgtype.Numeric     `json:"latitude"`
	Longitude pgtype.Numeric     `json:"longitude"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Voter struct {
	ID               string             `json:"id"`
	FullName         string             `json:"full_name"`
	Nin              string             `json:"nin"`
	Dob              pgtype.Date        `json:"dob"`
	State            string             `json:"state"`
	Lga              string             `json:"lga"`
	Phone            string             `json:"phone"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	VoterID          string             `json:"voter_id"`
	PollingStationID *string            `json:"polling_station_id"`
}
