// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polling_stations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPollingStations = `-- name: CountPollingStations :one
SELECT COUNT(*) FROM polling_stations
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR lga = $2)
  AND ($3::text IS NULL OR status = $3)
`

type CountPollingStationsParams struct {
	State  *string `json:"state"`
	Lga    *string `json:"lga"`
	Status *string `json:"status"`
}

func (q *Queries) CountPollingStations(ctx context.Context, arg CountPollingStationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPollingStations, arg.State, arg.Lga, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPollingStation = `-- name: CreatePollingStation :one
INSERT INTO polling_stations (id, code, name, state, lga, ward, address, latitude, longitude, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, name, state, lga, ward, address, latitude, longitude, status, created_at, updated_at
`

type CreatePollingStationParams struct {
	ID        string         `json:"id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	State     string         `json:"state"`
	Lga       string         `json:"lga"`
	Ward      string         `json:"ward"`
	Address   *string        `json:"address"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
	Status    string         `json:"status"`
}

func (q *Queries) CreatePollingStation(ctx context.Context, arg CreatePollingStationParams) (PollingStation, error) {
	row := q.db.QueryRow(ctx, createPollingStation,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.State,
		arg.Lga,
		arg.Ward,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Status,
	)
	var i PollingStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.State,
		&i.Lga,
		&i.Ward,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPollingStation = `-- name: GetPollingStation :one
SELECT id, code, name, state, lga, ward, address, latitude, longitude, status, created_at, updated_at FROM polling_stations
WHERE id = $1
`

func (q *Queries) GetPollingStation(ctx context.Context, id string) (PollingStation, error) {
	row := q.db.QueryRow(ctx, getPollingStation, id)
	var i PollingStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.State,
		&i.Lga,
		&i.Ward,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPollingStationByCode = `-- name: GetPollingStationByCode :one
SELECT id, code, name, state, lga, ward, address, latitude, longitude, status, created_at, updated_at FROM polling_stations
WHERE code = $1
`

func (q *Queries) GetPollingStationByCode(ctx context.Context, code string) (PollingStation, error) {
	row := q.db.QueryRow(ctx, getPollingStationByCode, code)
	var i PollingStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.State,
		&i.Lga,
		&i.Ward,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPollingStations = `-- name: ListPollingStations :many
SELECT id, code, name, state, lga, ward, address, latitude, longitude, status, created_at, updated_at FROM polling_stations
WHERE ($3::text IS NULL OR state = $3)
  AND ($4::text IS NULL OR lga = $4)
  AND ($5::text IS NULL OR status = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPollingStationsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	State  *string `json:"state"`
	Lga    *string `json:"lga"`
	Status *string `json:"status"`
}

func (q *Queries) ListPollingStations(ctx context.Context, arg ListPollingStationsParams) ([]PollingStation, error) {
	rows, err := q.db.Query(ctx, listPollingStations,
		arg.Limit,
		arg.Offset,
		arg.State,
		arg.Lga,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollingStation{}
	for rows.Next() {
		var i PollingStation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.State,
			&i.Lga,
			&i.Ward,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePollingStationStatus = `-- name: UpdatePollingStationStatus :one
UPDATE polling_stations
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, state, lga, ward, address, latitude, longitude, status, created_at, updated_at
`

type UpdatePollingStationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePollingStationStatus(ctx context.Context, arg UpdatePollingStationStatusParams) (PollingStation, error) {
	row := q.db.QueryRow(ctx, updatePollingStationStatus, arg.ID, arg.Status)
	var i PollingStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.State,
		&i.Lga,
		&i.Ward,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
