// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
)

type Querier interface {
	CountPollingStations(ctx context.Context, arg CountPollingStationsParams) (int64, error)
	CountVoters(ctx context.Context, arg CountVotersParams) (int64, error)
	CreatePollingStation(ctx context.Context, arg CreatePollingStationParams) (PollingStation, error)
	CreateVoter(ctx context.Context, arg CreateVoterParams) (Voter, error)
	DeleteVoter(ctx context.Context, id string) error
	ExistsVoterByNIN(ctx context.Context, nin string) (bool, error)
	GetPollingStation(ctx context.Context, id string) (PollingStation, error)
	GetPollingStationByCode(ctx context.Context, code string) (PollingStation, error)
	GetVoter(ctx context.Context, id string) (Voter, error)
	GetVoterByNIN(ctx context.Context, nin string) (Voter, error)
	ListPollingStations(ctx context.Context, arg ListPollingStationsParams) ([]PollingStation, error)
	ListVoters(ctx context.Context, arg ListVotersParams) ([]Voter, error)
	UpdatePollingStationStatus(ctx context.Context, arg UpdatePollingStationStatusParams) (PollingStation, error)
	UpdateVoterStatus(ctx context.Context, arg UpdateVoterStatusParams) (Voter, error)
}

var _ Querier = (*Queries)(nil)
