// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voters.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVoters = `-- name: CountVoters :one
SELECT COUNT(*) FROM voters
WHERE ($1::text IS NULL OR state = $1)
  AND ($2::text IS NULL OR status = $2)
`

type CountVotersParams struct {
	State  *string `json:"state"`
	Status *string `json:"status"`
}

func (q *Queries) CountVoters(ctx context.Context, arg CountVotersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVoters, arg.State, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoter = `-- name: CreateVoter :one
INSERT INTO voters (id, full_name, nin, dob, state, lga, phone)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, nin, dob, state, lga, phone, status, created_at, voter_id
`

type CreateVoterParams struct {
	ID       string      `json:"id"`
	FullName string      `json:"full_name"`
	Nin      string      `json:"nin"`
	Dob      pgtype.Date `json:"dob"`
	State    string      `json:"state"`
	Lga      string      `json:"lga"`
	Phone    string      `json:"phone"`
}

func (q *Queries) CreateVoter(ctx context.Context, arg CreateVoterParams) (Voter, error) {
	row := q.db.QueryRow(ctx, createVoter,
		arg.ID,
		arg.FullName,
		arg.Nin,
		arg.Dob,
		arg.State,
		arg.Lga,
		arg.Phone,
	)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Nin,
		&i.Dob,
		&i.State,
		&i.Lga,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.VoterID,
	)
	return i, err
}

const deleteVoter = `-- name: DeleteVoter :exec
DELETE FROM voters
WHERE id = $1
`

func (q *Queries) DeleteVoter(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVoter, id)
	return err
}

const existsVoterByNIN = `-- name: ExistsVoterByNIN :one
SELECT EXISTS (
    SELECT 1 FROM voters WHERE nin = $1
) AS exists
`

func (q *Queries) ExistsVoterByNIN(ctx context.Context, nin string) (bool, error) {
	row := q.db.QueryRow(ctx, existsVoterByNIN, nin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getVoter = `-- name: GetVoter :one
SELECT id, full_name, nin, dob, state, lga, phone, status, created_at, voter_id FROM voters
WHERE id = $1
`

func (q *Queries) GetVoter(ctx context.Context, id string) (Voter, error) {
	row := q.db.QueryRow(ctx, getVoter, id)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Nin,
		&i.Dob,
		&i.State,
		&i.Lga,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.VoterID,
	)
	return i, err
}

const getVoterByNIN = `-- name: GetVoterByNIN :one
SELECT id, full_name, nin, dob, state, lga, phone, status, created_at, voter_id FROM voters
WHERE nin = $1
`

func (q *Queries) GetVoterByNIN(ctx context.Context, nin string) (Voter, error) {
	row := q.db.QueryRow(ctx, getVoterByNIN, nin)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Nin,
		&i.Dob,
		&i.State,
		&i.Lga,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.VoterID,
	)
	return i, err
}

const listVoters = `-- name: ListVoters :many
SELECT id, full_name, nin, dob, state, lga, phone, status, created_at, voter_id FROM voters
WHERE ($3::text IS NULL OR state = $3)
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVotersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	State  *string `json:"state"`
	Status *string `json:"status"`
}

func (q *Queries) ListVoters(ctx context.Context, arg ListVotersParams) ([]Voter, error) {
	rows, err := q.db.Query(ctx, listVoters,
		arg.Limit,
		arg.Offset,
		arg.State,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voter{}
	for rows.Next() {
		var i Voter
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Nin,
			&i.Dob,
			&i.State,
			&i.Lga,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.VoterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoterStatus = `-- name: UpdateVoterStatus :one
UPDATE voters
SET status = $2
WHERE id = $1
RETURNING id, full_name, nin, dob, state, lga, phone, status, created_at, voter_id
`

type UpdateVoterStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateVoterStatus(ctx context.Context, arg UpdateVoterStatusParams) (Voter, error) {
	row := q.db.QueryRow(ctx, updateVoterStatus, arg.ID, arg.Status)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Nin,
		&i.Dob,
		&i.State,
		&i.Lga,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.VoterID,
	)
	return i, err
}
